#!/bin/bash
# Get the current admin password from Simple Auth Manager (Recommended Airflow 3.1.0 approach)

echo "=== Airflow Admin Password ==="
echo

# Detect which API server is running (Celery or Local mode)
API_SERVER=""

# Check for Celery mode API server
if docker compose ps | grep -q "airflow-api-server-celery.*Up"; then
    API_SERVER="airflow-api-server-celery"
# Check for Local mode API server
elif docker compose ps | grep -q "airflow-api-server.*Up"; then
    API_SERVER="airflow-api-server"
else
    echo "ERROR: Airflow API server is not running"
    echo "Please start services with either:"
    echo "  For local mode:  docker compose --profile local up -d"
    echo "  For Celery mode: docker compose --profile celery up -d"
    exit 1
fi

echo "Reading auto-generated password from Simple Auth Manager..."
echo

# Try to get password from the auto-generated file first
GENERATED_FILE="/opt/airflow/simple_auth_manager_passwords.json.generated"
if docker compose exec -T "$API_SERVER" test -f "$GENERATED_FILE" > /dev/null 2>&1; then
    echo "Reading from auto-generated password file..."
    ADMIN_PASSWORD=$(docker compose exec -T "$API_SERVER" python -c "import json; data=json.load(open('$GENERATED_FILE')); print(data.get('admin', 'Not found'))" 2>/dev/null | tr -d '\r')
else
    echo "Auto-generated file not found, reading from Simple Auth Manager directly..."
    # Get password using Simple Auth Manager API
    ADMIN_PASSWORD=$(docker compose exec -T "$API_SERVER" python -c "from airflow.api_fastapi.auth.managers.simple.simple_auth_manager import SimpleAuthManager; auth_manager = SimpleAuthManager(); users = auth_manager.get_users(); passwords = auth_manager.get_passwords(users); print(passwords.get('admin', 'Not found'))" 2>/dev/null | tr -d '\r')
fi

# Check if password was found
if [ "$ADMIN_PASSWORD" = "Not found" ]; then
    echo "ERROR: Admin password not found"
    echo "This could mean:"
    echo "  - Simple Auth Manager hasn't generated the password yet"
    echo "  - The admin user is not configured"
    echo "  - There's an issue with the authentication setup"
    echo
    echo "Try restarting the services: docker compose restart $API_SERVER"
    exit 1
fi

if [ -z "$ADMIN_PASSWORD" ]; then
    echo "ERROR: Could not retrieve admin password"
    echo "Please check the Airflow logs: docker compose logs $API_SERVER"
    exit 1
fi

echo "=== Login Credentials ==="
echo "Username: admin"
echo "Password: $ADMIN_PASSWORD"
echo
echo "Web UI: http://localhost:8080"
echo
echo "NOTE: This password is auto-generated by Simple Auth Manager."
echo "If you need to regenerate it, remove the generated file and restart:"
echo "  docker compose exec $API_SERVER rm -f /opt/airflow/simple_auth_manager_passwords.json.generated"
echo "  docker compose restart $API_SERVER"