@echo off
REM Get the current admin password from Simple Auth Manager (Recommended Airflow 3.1.0 approach)

echo === Airflow Admin Password ===
echo.

REM Detect which API server is running (Celery or Local mode)
set API_SERVER=

REM Check for Celery mode API server
docker compose ps | findstr "airflow-api-server-celery.*Up" >nul 2>&1
if %errorlevel% equ 0 (
    set API_SERVER=airflow-api-server-celery
    goto :check_server
)

REM Check for Local mode API server
docker compose ps | findstr "airflow-api-server.*Up" >nul 2>&1
if %errorlevel% equ 0 (
    set API_SERVER=airflow-api-server
    goto :check_server
)

:no_server
echo ERROR: Airflow API server is not running
echo Please start services with either:
echo   For local mode:  docker compose --profile local up -d
echo   For Celery mode: docker compose --profile celery up -d
exit /b 1

:check_server
echo Reading auto-generated password from Simple Auth Manager...
echo.

REM Try to get password from the auto-generated file first
set GENERATED_FILE=/opt/airflow/simple_auth_manager_passwords.json.generated
docker compose exec -T %API_SERVER% test -f %GENERATED_FILE% >nul 2>&1
if %errorlevel% equ 0 (
    echo Reading from auto-generated password file...
    for /f "tokens=*" %%i in ('docker compose exec -T %API_SERVER% python -c "import json; data=json.load(open('%GENERATED_FILE%')); print(data.get('admin', 'Not found'))" 2^>nul') do set ADMIN_PASSWORD=%%i
) else (
    echo Auto-generated file not found, reading from Simple Auth Manager directly...
    REM Get password using Simple Auth Manager API
    for /f "tokens=*" %%i in ('docker compose exec -T %API_SERVER% python -c "from airflow.api_fastapi.auth.managers.simple.simple_auth_manager import SimpleAuthManager; auth_manager = SimpleAuthManager(); users = auth_manager.get_users(); passwords = auth_manager.get_passwords(users); print(passwords.get('admin', 'Not found'))" 2^>nul') do set ADMIN_PASSWORD=%%i
)

REM Check if password was found
if "%ADMIN_PASSWORD%"=="Not found" (
    echo ERROR: Admin password not found
    echo This could mean:
    echo   - Simple Auth Manager hasn't generated the password yet
    echo   - The admin user is not configured
    echo   - There's an issue with the authentication setup
    echo.
    echo Try restarting the services: docker compose restart %API_SERVER%
    exit /b 1
)

if "%ADMIN_PASSWORD%"=="" (
    echo ERROR: Could not retrieve admin password
    echo Please check the Airflow logs: docker compose logs %API_SERVER%
    exit /b 1
)

echo === Login Credentials ===
echo Username: admin
echo Password: %ADMIN_PASSWORD%
echo.
echo Web UI: http://localhost:8080
echo.
echo NOTE: This password is auto-generated by Simple Auth Manager.
echo If you need to regenerate it, remove the generated file and restart:
echo   docker compose exec %API_SERVER% rm -f /opt/airflow/simple_auth_manager_passwords.json.generated
echo   docker compose restart %API_SERVER%